<?php
/* 
***
**** VARIÁVEIS DE AMBIENTE
***
*/ 

// DEFINES THE DEFAULT BACKEND FOLDER NAME
define("BACKEND_FOLDER_NAME", "backend");
// DEFINES DB CONNECTION HOST
define("DB_HOST", "localhost");
// DEFINES DB CONNECTION USERNAME
define("DB_USERNAME", "root");
// DEFINES DB CONNECTION PASSWORD
define("DB_PASSWORD", "");
// DEFINES DB CONNECTION DATABASE NAME
define("DB_NAME", "teste-madeira");

/* 
***
**** VARIÁVEIS PADRÃO DO PROJETO
***
*/ 

// DEFINES THE ROOT DIR PATH
define("DIR_ROOT", __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR);
// DEFINES THE MODELS DIR PATH
define("DIR_MODEL", DIR_ROOT . DIRECTORY_SEPARATOR . "Models");
// DEFINES THE CONTROLLERS DIR PATH
define("DIR_CONTROLLER", DIR_ROOT . DIRECTORY_SEPARATOR . "Controllers");
// DEFINES THE UPLOADS DIR PATH
define("DIR_UPLOADS", DIR_ROOT . DIRECTORY_SEPARATOR . "uploads");
// DEFINES IF THE CURRENT URL IS FROM A LOCALHOST ENVIROMENT
define("IS_LOCALHOST", $_SERVER['SERVER_NAME'] === "localhost" ? true : false);
// DEFINES CURRENT URL AS AN ARRAY FOR USAGE IN ROUTES
define(
    "ARRAY_REQUEST_URI",
    // EXPLODE THE CURRENT URL USING "/" AS REFERENCE
    explode(
        "/",
        // RETURN THE CURRENT URL WITHOUT "GET" PARAMETERS AND, IF LOCALHOST, WITHOUT FOLDER PATH PART
        substr(
            // RETURN THE CURRENT URL WITHOUT "GET" PARAMETERS
            strtok($_SERVER["REQUEST_URI"], '?'),
            // RETURN DIFFERENT OFFSET IF CURREN URL IS FROM A LOCALHOST ENVIROMENT
            strpos(strtok($_SERVER["REQUEST_URI"], '?'), "/", (IS_LOCALHOST ? 1 : 0))
                // ADDS 1 TO STRPOS TO REMOVE FIRST EMPTY PART
                + 1
                // ADDS BACKEND FOLDER NAME + / TO REMOVE IT FROM CURRENT URL ROUTE
                + strlen(BACKEND_FOLDER_NAME . "/")
        )
    )
);
// DEFINES DEFAULT PAGINATION QUANTITY
define("PAGINATION_QUANTITY", 10);
